#define TAPPING_TERM 300
#undef HOLD_ON_OTHER_KEY_PRESS

#define COMBO_STRICT_TIMER
#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_TERM 10
#define COMBO_HOLD_TERM 200
#define COMBO_MUST_HOLD_PER_COMBO
