#define TAPPING_TERM 200
#undef HOLD_ON_OTHER_KEY_PRESS

#define ONESHOT_TAP_TOGGLE 3
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define SPECULATIVE_HOLD
#define QUICK_TAP_TERM 200
#define FLOW_TAP_TERM 200
